# IPO Analyzer Configuration

# Data Collection Settings
data_collection:
  start_year: 2022
  end_year: 2025
  data_dir: "data/raw"

  # KRX API endpoints (to be configured with actual endpoints)
  api:
    base_url: "https://api.krx.co.kr"  # Replace with actual KRX API endpoint
    ipo_metadata_endpoint: "/ipo/metadata"
    intraday_prices_endpoint: "/market/intraday"
    timeout: 30
    retry_attempts: 3

# Feature Engineering Settings
features:
  transformers_dir: "data/processed"

  # Feature selection
  numerical_features:
    - ipo_price_confirmed
    - shares_offered
    - institutional_demand_rate
    - lockup_ratio
    - subscription_competition_rate
    - market_cap_ratio
    - total_offering_value
    - ipo_price_range_pct
    - price_positioning
    - demand_to_lockup_ratio
    - allocation_balance

  categorical_features:
    - listing_method
    - industry
    - theme

  # Thresholds for binary features
  thresholds:
    high_competition: 1000
    high_demand: 500

# Model Training Settings
model:
  type: "random_forest"  # Options: random_forest, gradient_boosting
  models_dir: "models"

  # Random Forest parameters
  random_forest:
    n_estimators: 100
    max_depth: 15
    min_samples_split: 5
    min_samples_leaf: 2
    random_state: 42
    n_jobs: -1

  # Gradient Boosting parameters
  gradient_boosting:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 5
    random_state: 42

  # Training settings
  test_size: 0.2
  cross_validation_folds: 5

# Prediction Settings
prediction:
  output_file: "../frontend/public/ipo_precomputed.json"

  # Targets to predict
  targets:
    - day0_high      # IPO day highest execution price
    - day0_close     # IPO day closing price
    - day1_close     # Next day closing price

  # Output format settings
  round_predictions: true
  include_metadata: true
  include_actual_values: false  # Set to true for validation

# Logging Settings
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/ipo_analyzer.log"
